# Only one ingredient can be defined per file.
type = "ingredient"			# Type must be one of ingredient, recipe, person, group.
name = "soy sauce"			# Name can be any UTF-8 string
author = "sudo-nano"		# Author field is for human readability and eventually sorting by author.
lastUpdated = "2024-05-16"	# Date of last update in YYYY-MM-DD format 

# Unit type to use for this ingredient
# Valid types are volumetric, mass, discrete
unitType = "volumetric"

# Density of this ingredient
# Density is not required, but you won't be able to convert between mass and volume
# unless it has a density value.
density.amount = 1.1	# Placeholder value: 1.1 g/mL
density.unit = "g/mL"	# TODO: measure actual density of soy sauce

[incompatibilities.dietary]
animalProduct = true
meat = true
egg = false
dairy = false
gluten = false
treeNuts = false
sesame = false
shellfish = false

[incompatibilities.religious]
halal = true
# Soy sauce is kosher, but doesn't meet the stricter definition of kosher kept
# by more orthodox jews during Passover. The minimum specification does not require
# an additional field for this, but users are free to add one.
kosher = true
leavened = false

# Table names must be snake case. Spaces are not supported in TOML table names.
[purchase_increments]
# Purchase increments is a list of lists. Each sub-list should contain exactly 3 items.
# The first item is the amount, the second item is the unit for that amount, and the 
# last item is the cost for that increment. 
increments = [ 
	[10.0, "mL", 1.00],	# This specifies that you can purchase 10.0 mL for $1.00. 
	[1.0, "L", 5.00]	# This specifies that you can purchase 1.0 L for $5.00. 
]
